### ISSUE TITLE
Compile error after changing .ioc

### ISSUE THREAD

**Issue by pablo-1424** [Seeed-Studio/LoRaWan-E5-Node#12]
Hello, 

My goal is to work with IrDA on the UART1 and once I've generated the code from the .ioc, there 12 compilation errors (see attachement 1).
Have someone had the same issue ? I have attached the modified UART in the .ioc (see attachement 2).

Thank you,

Pablo
[attachement1.txt](https://github.com/Seeed-Studio/LoRaWan-E5-Node/files/9886809/attachement1.txt)
![attachement2](https://user-images.githubusercontent.com/65167609/198546071-8f2518b4-22b5-4d48-8017-4dbdcc4f9d23.png)

**Comment by thonghatmit** [comment]
i have same issue, maybe code from repo does not lying in user section tag, so it break down the code when you generate ioc file. Do you have some solution ?

**Comment by mingzhangqun** [comment]
I'm interested if your problem has been solved.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
