### ISSUE TITLE
Tested on lsm110a

### ISSUE THREAD

**Issue by tcpipchip** [Seeed-Studio/LoRaWan-E5-Node#13]
https://lom204-cli-wisol.blogspot.com/2022/11/objetivo-este-documento-e-um-guia.html?m=1

**Comment by mingzhangqun** [comment]
Hello, could you please describe your problem in detail? Thank you!

**Comment by tcpipchip** [comment]
Hi @mingzhangqun
Wich problem ?

**Comment by mingzhangqun** [comment]
@tcpipchip About this issue, what can I do for you?

**Comment by tcpipchip** [comment]
If i recall, i solved that problem! And published that blog! Thanks

**Comment by mingzhangqun** [comment]
Ok, thanks for your feedback.
