### ISSUE TITLE
Help - Factory firmware -  E5's project folder

### ISSUE THREAD

**Issue by ShanmugaCA** [Seeed-Studio/LoRaWan-E5-Node#14]
Hi!

All the E5 modules are programmed by Seeed Studio and I want to do some changes to that firmware (FW)  and use it!

So, can anyone help me to locate the FW project folder of E5 module ?

Many thanks in advance,

Best regards,
Shanmuganathan

**Comment by sm-thamizha** [comment]
The factory firmware isn't available for public. You're either stuck with using the E5 modules as LoRa nodes with the factory firmware or you can reprogram the board entirely and use it for your application.

**Comment by ShanmugaCA** [comment]
It is unfortunate that the firmware of the E5 module is not available for users of the HW.

**Comment by bkrajendra** [comment]
HI @ShanmugaCA 
Although factory AT firmware is not opensource there is a FreeRTOS AT source under the folder Projects/Applications/FreeRTOS/FreeRTOS_LoRaWAN_AT
I am also working on it but could not get it working. Most of the AT command does not work. Might be I am missing something.

**Comment by ShanmugaCA** [comment]
Hi@bkrajendra,
Thanks for reply!
BTW, which Country specifi frequency you are trying?
I am intrested in making this work for India specific range and want to use the controller inside the chip than an external one.

**Comment by bkrajendra** [comment]
Update:
Projects/Applications/FreeRTOS/FreeRTOS_LoRaWAN_AT worked for me. The issue was the format of AT commands. 
AT+<CMD>=Value
this works. I was trying for IN865.
Find some notes:
**How to do OTAA**
In AT command source code change lorawan_conf.h file to uncomment **IN865** region

In Arduino Serial terminal set to 115200 + Carriage Return
**AT commands to use:**
Change Region: AT+BAND=7
Join OTAA: AT+JOIN=1
Send : AT+SEND=1:1:123

**Comment by bkrajendra** [comment]
I am also trying to use the internal STM32 for creating a custom sensor node.
FYI, there is an Arduino support for this https://github.com/stm32duino/Arduino_Core_STM32
And a library which I am also working on to make it work. https://github.com/stm32duino/STM32LoRaWAN
check these out.
I am currently stuck at https://github.com/stm32duino/STM32LoRaWAN/issues/24

**Comment by mingzhangqun** [comment]
@ShanmugaCA @bkrajendra  Hello, I'm interested if your problem has been solved.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
