### ISSUE TITLE
FreeRTOS examples do not compile under STM32CubeIDE v 1.12

### ISSUE THREAD

**Issue by jkuzma** [Seeed-Studio/LoRaWan-E5-Node#15]
The FreeRTOS examples in this repository do not compile properly with the latest version of STM32CubeIDE.

**Comment by mingzhangqun** [comment]
@jkuzma Hello, I'm interested if your problem has been solved.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Comment by cristinel08** [comment]
Hello,
I keep getting multiple definition error of hlptim1 when trying to compile FreeRTOS_LoRaWAN_AT. 
I am using STM32CubeIDE v1.16

**Comment by Lesords** [comment]
> Hello, I keep getting multiple definition error of hlptim1 when trying to compile FreeRTOS_LoRaWAN_AT. I am using STM32CubeIDE v1.16

@mingzhangqun help with this one

**Comment by mingzhangqun** [comment]
@cristinel08 Hello, I'm reproducing the problem.

**Comment by mingzhangqun** [comment]
I have tried it on the latest IDE and it is ok.
![image](https://github.com/user-attachments/assets/cf1cce6f-e297-4d68-9c78-22755c51ee2f)
![image](https://github.com/user-attachments/assets/e454e6cd-7770-46e8-af60-c7546e940ffa)
