### ISSUE TITLE
Decode of received Lorawan message.

### ISSUE THREAD

**Issue by Fatihalparslan** [Seeed-Studio/LoRaWan-E5-Node#17]
I used LoRa E5 mini and E5-end node code. I received base64 format message like this  "ACcQGgH0/j4JDQUDqwAA" from gateway interface Is there any formula to decode

**Comment by Lamb1993** [comment]
That should be Base64. You'll just need to pay attention to how many bytes each part of the payload is (temperature, for example, is 1 byte)

**Comment by mingzhangqun** [comment]
@Fatihalparslan Hello, I'm interested if your problem has been solved.
