### ISSUE TITLE
Wio-E5 with Helium Network

### ISSUE THREAD

**Issue by mnett0** [Seeed-Studio/LoRaWan-E5-Node#18]
Hey, 

I'm looking to run my custom board with a Wio-E5 module on the Helium network. 

1) I have a Helium gateway at home, everything is ok 
2) I've created a device on the Helium console, everything should be ok, it's not the first time I make devices communicate on it. 
3) I've used the LoRaWan_End_Node example code, I've managed to compile and push the .hex onto the module. 
4) I set the App Key (lsb format) to AppKey and NwkKey in the se-identity.h file.

This is what I get from the module: 
```
APP_VERSION:        V1.1.0
MW_LORAWAN_VERSION: V2.3.0
MW_RADIO_VERSION:   V1.1.0
###### OTAA ######
###### AppKey:      2B:7E:15:16:28:AE:D2:A6:AB:F7:15:88:09:CF:4F:3C (myHeliumAppKey)
###### NwkKey:      2B:7E:15:16:28:AE:D2:A6:AB:F7:15:88:09:CF:4F:3C (myHeliumAppKey)
###### ABP  ######
###### AppSKey:     2B:7E:15:16:28:AE:D2:A6:AB:F7:15:88:09:CF:4F:3C 
###### NwkSKey:     2B:7E:15:16:28:AE:D2:A6:AB:F7:15:88:09:CF:4F:3C
###### DevEui:  00:00:F9:00:52:00:B5:00 (myHeliumDevEui)
###### AppEui:  00:00:F9:00:8F:00:4A:00 (myHeliumAppEui)
###### DevAddr: 00:3B:BD:76
0s036:TX on freq 868300000 Hz at DR 0
1s522:MAC txDone
6s555:RX_1 on freq 868300000 Hz at DR 0
6s753:IRQ_RX_TX_TIMEOUT
6s753:MAC rxTimeOut
7s555:RX_2 on freq 869525000 Hz at DR 0
7s753:IRQ_RX_TX_TIMEOUT
7s753:MAC rxTimeOut

###### = JOIN FAILED
30s040:temp= 57
30s041:VDDA= 254
30s044:TX on freq 868100000 Hz at DR 0
31s531:MAC txDone
36s564:RX_1 on freq 868100000 Hz at DR 0
36s762:IRQ_RX_TX_TIMEOUT
36s762:MAC rxTimeOut
37s564:RX_2 on freq 869525000 Hz at DR 0
37s762:IRQ_RX_TX_TIMEOUT
37s762:MAC rxTimeOut

###### = JOIN FAILED
```
Some questions :
- Is it normal to have the temp at 57? On the internet I see more coherent values like 22. 

- Isn't the "LoRaWan" version of the module too high to work with Helium Network? 
I have : 
```
APP_VERSION: V1.1.0
MW_LORAWAN_VERSION: V2.3.0
MW_RADIO_VERSION: V1.1.0
```
And I see : "_The Helium Network supports any LoRaWAN capable device meeting the v1.0.2, v1.0.3, or v1.0.4 specification._" Here https://docs.helium.com/iot/devices/

If yes, is it possible to downgrade the LoRaWan version of the module? 

- Do these logs tell you anything? 

Thank you

**Comment by mingzhangqun** [comment]
@mnett0 Hello, I'm interested if your problem has been solved.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
