### ISSUE TITLE
Downstream traffic

### ISSUE THREAD

**Issue by ejschiller** [Seeed-Studio/LoRaWan-E5-Node#19]
Dear All, I use the example application based on the simple sequencer implementation. While everything is fine on the upstream, I don't receive packets on the downstream scheduled by the TTN backend. Most of the time, I receive the RX timeout on both reception windows after a TX. However, sometimes, downlink packets go through. What might be the reason for this behavior? I experienced this with LoRaWAN Specification 1.0.0 with ABP and LoRaWAN Specification 1.0.2 with OTAA. LoRaWAN Specification 1.1.0 does not work for me at all, as the join fails. Thanks! ES

**Comment by mingzhangqun** [comment]
I'm interested if your problem has been solved.

**Comment by ejschiller** [comment]
> I'm interested if your problem has been solved.

We were unable to resolve this issue last year. I can try the current version of your software.

**Comment by mingzhangqun** [comment]
It's great, I'm glad to wait for your feedback.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
