### ISSUE TITLE
DOWNLINK NOT WORK with ADR Active ON : DR:5 | PWR:7  ==> No downlink

### ISSUE THREAD

**Issue by pierre-microlide** [Seeed-Studio/LoRaWan-E5-Node#21]
Hi,
i use Wio-E5 mini board with LoraWan app. All is ok with my gateway to join or read datas from sensor. 
But, if i use the ADR=On to save power, when SF is less than 12, downlink are not received by the sensor ? The downlink is sent by the gateway.
I don't understand why ? Please, can you help me ?
Thanks
Regards
Pierre

**Comment by mingzhangqun** [comment]
@pierre-microlide I'm interested if your problem has been solved.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
