### ISSUE TITLE
I can not find pin PC2 for LoRa-E5 DevBoard

### ISSUE THREAD

**Issue by thonghatmit** [Seeed-Studio/LoRaWan-E5-Node#22]
I want to assgin MISO pin for LoRa-E5 DevBoard, but it is not possible to fin pin PC2 on DevBoard, although in Pin Diagram in STM32CubeIDE have shown the pin PC2, where can i find this PC2 pin on DevBoard
![hoiPin](https://github.com/Seeed-Studio/LoRaWan-E5-Node/assets/87261328/89d76282-8605-41eb-b8ec-353d71cad541)
[LoRa-E5_Dev_Board_schematic.pdf](https://github.com/user-attachments/files/15802491/LoRa-E5_Dev_Board_schematic.pdf)

**Comment by HeadBoffin** [comment]
The STM32CubeMX tool shows the pins on the chip - it has no knowledge of the board that it is placed on - and if you review the documentation you will find both the schematic and the wiki and more shows that the module does not connect the PC2 to the connectors.

**Comment by mingzhangqun** [comment]
@thonghatmit Hello, I'm interested if your problem has been solved.

**Comment by HeadBoffin** [comment]
That's a bit meta - if they want to use PC2 they can't use it with the Wio-E5 unless you make a change - otherwise any other discussion is pointless because it's just not available on the module - so may as well be closed.
