### ISSUE TITLE
How to Transmit Data Directly Between Two LoRa-E5 Mini Modules?

### ISSUE THREAD

**Issue by Nikitanagar** [Seeed-Studio/LoRaWan-E5-Node#23]
Hello everyone,
I'm currently working on a project involving two LoRa-E5 Mini modules, and I need to transmit data directly from one module to the other. My goal is to establish a peer-to-peer (P2P) communication between the two modules without relying on AT commands or any external networks like The Things Network (TTN).

**What I want :**
I don't want to use TTN just want to use LoRa in a simpler point-to-point communication mode.

**Questions:**
What steps or configurations are needed to enable direct communication between the two LoRa-E5 Mini modules?
How can I set up the modules to transmit and receive data in a simple P2P mode?
Are there any example codes or specific libraries that can facilitate this setup?
Additional Information:
I'm not using any LoRaWAN network for this project; I want the two modules to communicate directly.
I’m using STM32CubeIDE for development.
Any guidance, sample code, or documentation references would be greatly appreciated!

Thank you!

**Comment by johflo** [comment]
You can try this code https://github.com/johflo/Seeed-Lora-e5 .
It's based on the STM32 PingPong example.

**Comment by mingzhangqun** [comment]
@Nikitanagar I'm interested if your problem has been solved.

**Comment by Nikitanagar** [comment]
I used [RadioLib](https://github.com/jgromes/RadioLib) library, so can test it. I hope it will help.

**Comment by mingzhangqun** [comment]
@Nikitanagar It's great, thanks a lot.
