### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by simon88** [Seeed-Studio/LoRaWan-E5-Node#3]
It would be nice if you can provide an example for poit to point comunication withe Lora-E5 module

**Comment by lakshanthad** [comment]
Hello @simon88,

Currently, we only have a P2P communication example with Grove-Lora-E5:
https://wiki.seeedstudio.com/Grove_LoRa_E5_New_Version/#grove-lora-e5-p2p-example

Unfortunately, we do not have the resources to provide a P2P example for the E5 mini and E5 development kit at the moment.
