### ISSUE TITLE
Error: Unable to get core ID at step 12

### ISSUE THREAD

**Issue by Julie97434** [Seeed-Studio/LoRaWan-E5-Node#4]
Hello, 
I followed all the steps to the letter, but I have an error when I execute step 12. I want to program the LoRa E5 mini.

At step 11: I click on the connect button in STM32CubeProgrammer and get the following information:
![cubepro_git](https://user-images.githubusercontent.com/44209157/164227297-f6417d0a-a74d-43a2-927e-82257aab8643.png)

For step 12: I select my .hex file and as soon as I click on `Start Programming` I get the error: `Error: Unable to get core ID` and the board disconnects from STM32Cube pro. As in the following photo: 
![errorcubepro_git](https://user-images.githubusercontent.com/44209157/164227462-84725e3b-6487-497f-bd72-5914eacdc701.png)

What does that mean ? Does this have anything to do with the devEUI I write in the `se-identity.h` file?

**Comment by lakshanthad** [comment]
Hello @Julie97434,

Have you set the "Read Out Protection" to AA?

Best Regards,
Lakshantha

**Comment by Julie97434** [comment]
Hello @lakshanthad , thank you for your answer. 

I misread the information, it's the ST-Link card (nucleoL073RZ) that disconnects after the successful upload of the program in the LoRaE5-mini. So everything works !

**Comment by lakshanthad** [comment]
That's great!
