### ISSUE TITLE
"Multiple definitions of hlptim1" when running FreeRTOS project 

### ISSUE THREAD

**Issue by ES0R** [Seeed-Studio/LoRaWan-E5-Node#5]
I completed the LoraWAN end node tutorial for the LoRA E5 Dev board (https://wiki.seeedstudio.com/LoRa_E5_Dev_Board/#freertos-lorawan) and continued to the RTOS part. However, when running the code unaltered, it fails to compile. This is the case for both FreeRTOS and FreeRTOS_AT. I have been unable to locate the error. I have attached the console log for when it fails.

[log.txt](https://github.com/Seeed-Studio/LoRaWan-E5-Node/files/8610726/log.txt)

**Comment by rpiper** [comment]
I just ran into this same issue when building the different FreeRTOS examples. There is a simple fix.

For each project, in Core/Inc/main.h, find the line:

`LPTIM_HandleTypeDef hlptim1;`

and change it to:

`extern LPTIM_HandleTypeDef hlptim1;`

and all three projects will build without any errors or warnings!

**Comment by rpiper** [comment]
Just added a pull request with these changes #6

**Comment by lakshanthad** [comment]
It is done.
https://github.com/Seeed-Studio/LoRaWan-E5-Node/pull/6
