### ISSUE TITLE
FreeRTOS LoRaWAN AT Command issues

### ISSUE THREAD

**Issue by ES0R** [Seeed-Studio/LoRaWan-E5-Node#7]
When running the given AT commands from the FREERTOS LoRaWAN AT build some of the commands fail. 
I was able to connect to TTN using "AT+JOIN=1" and I was able to use "AT?" but using other commands seems to just result in "AT_ERROR". For example, using "AT+VER" gives an error.  I have been unable to locate the error, can this be replicated by any others?

**Comment by lakshanthad** [comment]
Hello,

Please help me answer the following:

- What is the exact E5 product you are using?
- What serial terminal application are you using to connect with LoRa E5?
- What are the connection parameters such as the baud rate you have set up?
- Did you add '\r\n' at the end of the command?

Thank you

**Comment by ES0R** [comment]
Hello

Sorry for late answer: 
I'm using the LoRa-E5 Dev Board. 
I'm using arduino's serial monitor
I'm using 115200 as baudrate
Yes

**Comment by lakshanthad** [comment]
Hello,

I will test this and get back to you.

**Comment by lakshanthad** [comment]
Hello,

I have tested this and you should enter the commands as follows:

To get a value: 
`AT+<CMD>=?`

<div align='left'><img src='https://user-images.githubusercontent.com/20147381/170973041-fcbc527b-903c-4f8a-8633-9dea199fc692.png' width='500'></div>

Therefore to get the firmware version, you should enter:
`AT+VER=?`

<div align='left'><img src='https://user-images.githubusercontent.com/20147381/170973444-e942588e-aa9d-4a33-98d7-f174fe8c0357.png' width='500'></div>

Make sure of these settings also:
<div align='left'><img src='https://user-images.githubusercontent.com/20147381/170973212-907740f9-cf54-4881-a4ac-b46fd1b49ce3.png' width='500'></div>

Please let me know how it goes.

Thank you.

**Comment by shawnventi** [comment]
I believe that some confusion in this issue might be from the fact that the factory AT firmware has a different AT command spec than the project included in this repo.

The factory AT firmware follows this spec: https://files.seeedstudio.com/products/317990687/res/LoRa-E5%20AT%20Command%20Specification_V1.0%20.pdf

@lakshanthad - Is it possible to get a copy of the factory AT firmware that can be used? I'm not looking for the source just a compiled copy that will work on the LoRa-E5 mini dev boards.

**Comment by bkrajendra** [comment]
Hi, I am also trying to work with FreeRTOS AT firmware.
I can get a response for AT?, AT+VER=? etc. But whenever I try to set the value, I get Error AT_PARAM_ERROR
What is the right format to set value with AT.
I tried AT+DADDR=xxxx, but with no success.
