### ISSUE TITLE
IOC Faliure

### ISSUE THREAD

**Issue by e135193** [Seeed-Studio/LoRaWan-E5-Node#8]
FreeRTOS projects works well but there is a problem with the "FreeRTOS_LoRaWAN.ioc" file. When I open the IOC file, configuration is not showing correctly. It seems like it is a fresh project. Could you please check and correct it.

In addition, I can not debug the End Node project. stlink loses connection with the MCU.

![Capture](https://user-images.githubusercontent.com/7726650/169406493-190b0cf2-6927-4f9a-8301-060935221cb2.PNG)

**Comment by lakshanthad** [comment]
Hello,

I will check about the IOC file.

In the meantime, could you please elaborate more on the STLink disconnection?

1, Can I know the exact LoRa E5 product you are using? E5 mini/ dev board?
2, Does it connect successfully for the first time?
3, After how long it gets disconnected? And is it random or within same time interval?
4, Can I see a photo of the connection between STLink and E5?
5, Have you set "Read Out Protection" as AA in "STM32CubeProgrammer"?

Thank you.

**Comment by sjackson2011** [comment]
Any answer to the original .ioc file problem? It seems that the project has not been built with the .ioc file included. Specifically I am using the w5_mini  FreeRTOS_LoRaWAN_AT project

**Comment by mingzhangqun** [comment]
I'm interested if your problem has been solved.
